import { z } from "zod";

export const BizCode = {
  AUTH_ACCESS_EXPIRED: "AUTH.ACCESS_EXPIRED",
  AUTH_ACCESS_INVALID: "AUTH.ACCESS_INVALID",
  AUTH_ACCESS_MISSING: "AUTH.ACCESS_MISSING",
  AUTH_FORBIDDEN: "AUTH.FORBIDDEN",
  AUTH_INVALID_CREDENTIALS: "AUTH.INVALID_CREDENTIALS",
  AUTH_REFRESH_INVALID: "AUTH.REFRESH_INVALID",
  AUTH_REFRESH_MISSING: "AUTH.REFRESH_MISSING",
  AUTH_REFRESH_REPLAYED: "AUTH.REFRESH_REPLAYED",
  AUTH_SESSION_REVOKED: "AUTH.SESSION_REVOKED",
  COMMON_INVALID_REQUEST: "COMMON.INVALID_REQUEST",
  COMMON_NOT_FOUND: "COMMON.NOT_FOUND",
  ROLE_APPLICATION_NOT_FOUND: "ROLE.APPLICATION_NOT_FOUND",
  ROLE_CODE_CONFLICT: "ROLE.CODE_CONFLICT",
  ROLE_NOT_FOUND: "ROLE.NOT_FOUND",
  ROLE_PROTECTED: "ROLE.PROTECTED",
  SYSTEM_DATABASE_UNAVAILABLE: "SYSTEM.DATABASE_UNAVAILABLE",
  SYSTEM_INTERNAL_ERROR: "SYSTEM.INTERNAL_ERROR",
  SYSTEM_STORAGE_UNAVAILABLE: "SYSTEM.STORAGE_UNAVAILABLE",
  SYSTEM_UPSTREAM_TIMEOUT: "SYSTEM.UPSTREAM_TIMEOUT",
} as const;

export const BizCodeSchema = z.enum(BizCode);

export type BizCodeValue = (typeof BizCode)[keyof typeof BizCode];
